
services:
  db-films-top:
    image: postgres:latest
    container_name: db-films-top
    environment:
      POSTGRES_DB: films-top
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./db_sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - films-top_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my-flask-app
    command: ["sh", "-c", "wait-for-it.sh db-films-top:5432 -- flask run --host=0.0.0.0"]
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db-films-top


networks:
  my_network:
    driver: bridge

volumes:
  films-top_data: