services:
  db-films-top:
    image: postgres:latest
    container_name: db-films-top
    environment:
      POSTGRES_DB: films-top
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - films-top_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis_films_top
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  films-top_data:
  redis-data: